[build]
  command = "echo 'No build needed for static OAuth callbacks'"
  publish = "public"

# Redirect legacy domain to new domain
[[redirects]]
  from = "https://rideready.icu/*"
  to = "https://veloready.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.rideready.icu/*"
  to = "https://veloready.app/:splat"
  status = 301
  force = true

# Serve apple-app-site-association without .json extension
[[redirects]]
  from = "/.well-known/apple-app-site-association"
  to = "/apple-app-site-association.json"
  status = 200
  force = true

[[headers]]
  for = "/apple-app-site-association.json"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/.well-known/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=3600"

# OAuth callback endpoints (if using Netlify Functions)
[[redirects]]
  from = "/auth/strava/callback"
  to = "/.netlify/functions/strava-callback"
  status = 200

[[redirects]]
  from = "/auth/intervals/callback"
  to = "/.netlify/functions/intervals-callback"
  status = 200

[build.environment]
  NODE_VERSION = "18"
