#!/bin/bash
# Quick startup performance test
# Run this after installing on device to verify <2s startup

set -e

echo "📱 Startup Performance Test"
echo "================================"
echo ""
echo "🎯 Target: <2 seconds to interactive UI"
echo "📊 Metrics to verify:"
echo ""
echo "✅ Phase 1 (<200ms):"
echo "   - UI appears instantly"
echo "   - Rings show data (cached or yesterday's)"
echo "   - No full-screen spinner blocking"
echo ""
echo "✅ Phase 2 (1-2s):"
echo "   - Scores update smoothly"
echo "   - Ring animations visible"
echo "   - All 3 rings show today's values"
echo ""
echo "✅ Phase 3 (2-10s, background):"
echo "   - Activities populate gradually"
echo "   - No UI freezing"
echo "   - User can interact while loading"
echo ""
echo "================================"
echo ""
echo "📝 Manual Test Steps:"
echo ""
echo "1. Force quit the app"
echo "2. Launch and start timer"
echo "3. Note when UI appears (should be <200ms)"
echo "4. Note when rings update (should be <2s)"
echo "5. Check console logs for timing:"
echo ""
echo "   Look for these logs:"
echo "   🎯 PHASE 1: Instant Display"
echo "   ⚡ PHASE 1 complete in X.XXXs"
echo "   ✅ UI displayed instantly"
echo "   🎯 PHASE 2: Critical Updates"
echo "   ✅ PHASE 2 complete in X.XXs"
echo "   📊 [INCREMENTAL] Fetching today's activities"
echo ""
echo "================================"
echo ""
echo "🧪 Test Scenarios:"
echo ""
echo "1. Cold start (first launch)"
echo "   - Expected: <500ms (no cache)"
echo ""
echo "2. Warm start (second launch)"
echo "   - Expected: <200ms (cached)"
echo ""
echo "3. Airplane mode"
echo "   - Expected: <100ms (all cached)"
echo ""
echo "4. After force quit"
echo "   - Expected: <200ms (cache persists)"
echo ""
echo "================================"
echo ""
echo "✅ Success Criteria:"
echo "   - UI appears in <200ms"
echo "   - Scores updated in <2s"
echo "   - No blocking spinners"
echo "   - Smooth animations"
echo "   - Activities load incrementally"
echo ""
echo "Ready to test! Launch the app and observe timing."

