name: Full E2E Tests

on:
  push:
    branches: [main]
  schedule:
    # Run nightly at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  # Tier 3: Full E2E suite after merging to main
  full_e2e:
    runs-on: macos-14
    timeout-minutes: 60  # Prevent infinite runs
    strategy:
      matrix:
        # Reduced matrix to prevent log explosion
        device: ['iPhone 15 Pro']  # Only test on one device for now
        ios_version: ['18.0']      # Test on iOS 18.0 (latest stable)
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'
      - name: Setup Java for Maestro
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install Maestro
        run: |
          brew tap mobile-dev-inc/tap
          brew install maestro
      - name: Build iOS App
        run: |
          xcodebuild build \
            -project VeloReady.xcodeproj \
            -scheme VeloReady \
            -destination 'platform=iOS Simulator,name=${{ matrix.device }},OS=${{ matrix.ios_version }}' \
            -configuration Debug \
            SKIP_INSTALL=NO \
            BUILD_DIR=$(pwd)/build \
            -quiet \
            -hideShellScriptEnvironment
      - name: Create Results Directory
        run: mkdir -p maestro-results/
        
      - name: Run Full E2E Suite
        run: |
          # Run all E2E test scenarios with controlled output
          echo "Starting E2E tests on ${{ matrix.device }} iOS ${{ matrix.ios_version }}"
          set -e  # Exit on any error
          maestro test tests/e2e/scenarios/ --format junit --output maestro-results/ || {
            echo "E2E tests failed, but continuing to archive results"
            exit 1
          }
        env:
          MAESTRO_LOG_LEVEL: WARN  # Reduce log verbosity
      - name: Archive Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-results-${{ matrix.device }}-${{ matrix.ios_version }}
          path: maestro-results/
