name: Full E2E Tests

on:
  push:
    branches: [main]
  schedule:
    # Run nightly at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  # Tier 3: Full E2E suite after merging to main
  full_e2e:
    runs-on: macos-14
    strategy:
      matrix:
        device: ['iPhone 15 Pro', 'iPhone SE (3rd generation)']
        ios_version: ['17.0', '18.0']
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'
      - name: Setup Java for Maestro
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install Maestro
        run: |
          brew tap mobile-dev-inc/tap
          brew install maestro
      - name: Build iOS App
        run: |
          xcodebuild build \
            -project VeloReady.xcodeproj \
            -scheme VeloReady \
            -destination 'platform=iOS Simulator,name=${{ matrix.device }},OS=${{ matrix.ios_version }}' \
            -configuration Debug \
            SKIP_INSTALL=NO \
            BUILD_DIR=$(pwd)/build
      - name: Run Full E2E Suite
        run: |
          # Run all E2E test scenarios
          maestro test tests/e2e/scenarios/
      - name: Archive Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-results-${{ matrix.device }}-${{ matrix.ios_version }}
          path: maestro-results/
