name: Integration Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  backend-integration:
    runs-on: ubuntu-latest
    environment: Test
    
    steps:
      - uses: actions/checkout@v4
        with:
          repository: markboulton/veloready-website
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run integration tests
        run: npm run test:integration
        env:
          SUPABASE_URL: ${{ secrets.TEST_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.TEST_SUPABASE_KEY }}
          STRAVA_CLIENT_ID: ${{ secrets.TEST_STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.TEST_STRAVA_CLIENT_SECRET }}
          
  ios-integration:
    runs-on: macos-14
    
    steps:
      - uses: actions/checkout@v4
        with:
          repository: markboulton/veloready
          
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
          
      - name: Run integration tests
        run: |
          xcodebuild test \
            -scheme VeloReady \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
            -only-testing:VeloReadyTests/Integration \
            -resultBundlePath ./test-results.xcresult
            
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: ./test-results.xcresult
